(function(){
  'use strict';
  if(document.querySelector('.site-nav'))return;
  if(/(?:^|\/)index\.html$/.test(location.pathname)||location.pathname.endsWith('/'))document.body.classList.add('site-home');
  const stylesheet=document.createElement('link');stylesheet.rel='stylesheet';stylesheet.href='site-nav.css?v=account-popover-right-2';const menuStyles=document.createElement('link');menuStyles.rel='stylesheet';menuStyles.href='site-nav-menu.css?v=category-drawer-gradual-2';const typographyStyles=document.createElement('link');typographyStyles.rel='stylesheet';typographyStyles.href='typography-spacing.css?v=readability-1';document.head.appendChild(typographyStyles);
  const signedIn=()=>!!(sessionStorage.getItem('clearly_access_token')||localStorage.getItem('clearly_access_token'));
  let profile={};try{profile=JSON.parse(localStorage.getItem('clearly_profile')||'{}')||{};}catch(error){}
  const fallbackCategories=[
    ['Home Care & Cleaning','home-care-cleaning','assets/categories/floor-care-living-hall.png'],
    ['Restaurant & Food Service','restaurant-food-service','assets/categories/restaurant-food-service.png'],
    ['Healthcare & Institutions','healthcare-institutions','assets/categories/healthcare-institutions.png'],
    ['Laundry Chemicals','laundry-chemicals','assets/categories/laundry-chemicals.png'],
    ['Swimming Pool Chemicals','swimming-pool-chemicals','assets/categories/swimming-pool-chemicals.png'],
    ['Hotel & Hospitality','hotel-hospitality','assets/categories/hotel-hospitality.png'],
    ['Specialty Chemicals','specialty-chemicals','assets/categories/specialty-chemicals.png'],
    ['Construction Chemicals','construction-chemicals','assets/categories/construction-chemicals.png']
  ];
  const categoryApi=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8080/api/categories':'/api/categories';
  const homepageApi=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8080/api/homepage':'/api/homepage';
  const validAccent=value=>/^#[0-9a-f]{6}$/i.test(String(value||''))?String(value):'#557A9B';
  const accentShade=(hex,amount)=>{const value=validAccent(hex).slice(1),channels=[0,2,4].map(index=>parseInt(value.slice(index,index+2),16));return '#'+channels.map(channel=>Math.max(0,Math.min(255,Math.round(channel+(amount<0?channel*amount:(255-channel)*amount)))).toString(16).padStart(2,'0')).join('');};
  const applyThemeAccent=value=>{const accent=validAccent(value),root=document.documentElement.style;root.setProperty('--blue',accent);root.setProperty('--site-blue',accent);root.setProperty('--blue-dark',accentShade(accent,-.18));root.setProperty('--site-blue-dark',accentShade(accent,-.18));root.setProperty('--site-blue-soft',accentShade(accent,.88));document.documentElement.dataset.themeAccent=accent.slice(1);};
  applyThemeAccent();
  const categoryImages={
    'home-care-cleaning':'assets/categories/floor-care-living-hall.png','restaurant-food-service':'assets/categories/restaurant-food-service.png','healthcare-institutions':'assets/categories/healthcare-institutions.png','laundry-chemicals':'assets/categories/laundry-chemicals.png','swimming-pool-chemicals':'assets/categories/swimming-pool-chemicals.png','hotel-hospitality':'assets/categories/hotel-hospitality.png','specialty-chemicals':'assets/categories/specialty-chemicals.png','construction-chemicals':'assets/categories/construction-chemicals.png'
  };
  const escapeHtml=value=>String(value==null?'':value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const nav=document.createElement('header');nav.className='site-nav';nav.innerHTML=`<a class="site-logo" href="index.html">Zarnik<span>.</span></a><button class="site-category-button" id="site-categories"><svg viewBox="0 0 24 24"><rect x="4" y="3" width="16" height="18" rx="1"/><path d="M8 7h8M8 11h8M8 15h8"/></svg><span>Shop All Categories</span></button><form class="site-search"><input aria-label="Search" placeholder="Search hotel supplies, products, and brands…"><button aria-label="Search">⌕</button></form><div class="site-actions"><div class="site-account-wrap"><a class="site-action" id="site-account" href="${signedIn()?'profile.html':'account.html'}" aria-label="My account"><svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M4.5 20c.7-3.5 3.3-5.4 7.5-5.4s6.8 1.9 7.5 5.4"/></svg></a><div class="site-account-card">${signedIn()?`<strong>Hello ${profile.name||'there'}</strong><span>Manage your companies, orders and account.</span><a href="profile.html">My account</a><button id="site-logout">Log out</button>`:`<strong>Welcome</strong><span>To access account and manage orders</span><a href="account.html">Login / Signup</a>`}</div></div><a class="site-action" href="cart.html" aria-label="Cart"><svg viewBox="0 0 24 24"><path d="M3.8 5h2.3l1.5 9.5h10.2l2.1-6.8H7"/><circle cx="10" cy="18.5" r="1.3"/><circle cx="17" cy="18.5" r="1.3"/></svg><i class="site-badge" data-site-cart>0</i></a><a class="site-action" href="wishlist.html" aria-label="Wishlist"><svg viewBox="0 0 24 24"><path d="M20.5 8.6c0 5.1-8.5 10-8.5 10s-8.5-4.9-8.5-10A4.6 4.6 0 0 1 12 6.1a4.6 4.6 0 0 1 8.5 2.5Z"/></svg><i class="site-badge" data-site-wish>0</i></a></div>`;
  nav.querySelector('.site-logo').innerHTML='Clearly<span>.</span>';
  if(location.pathname.endsWith('/products.html')||location.pathname.endsWith('products.html'))nav.querySelector('.site-search input').id='search';
  const categoryButton=nav.querySelector('#site-categories');
  categoryButton.querySelector('span').textContent='Categories';
  categoryButton.insertAdjacentHTML('beforebegin','<nav class="site-main-links"><a href="index.html">Home</a><a href="products.html">Shop</a></nav>');
  categoryButton.insertAdjacentHTML('afterend','<nav class="site-main-links site-main-links-after"><a href="index.html#about">About Us</a><a href="index.html#offers">Offers</a></nav>');
  const navCenter=document.createElement('div');navCenter.className='site-nav-center';const firstLinks=nav.querySelector('.site-main-links');firstLinks.before(navCenter);navCenter.append(firstLinks,categoryButton,nav.querySelector('.site-main-links-after'));
  const overlay=document.createElement('div');overlay.className='site-overlay';overlay.innerHTML=`<aside class="site-drawer" role="dialog" aria-modal="true" aria-label="Shop all categories"><div class="site-drawer-head"><h2>Shop all categories</h2><button id="site-close" aria-label="Close">×</button></div><div class="site-category-list" id="site-category-list"></div></aside>`;
  nav.style.visibility='hidden';overlay.style.visibility='hidden';document.body.prepend(nav);document.body.appendChild(overlay);
  const footer=document.createElement('footer');footer.className='clearly-footer';footer.innerHTML=`<section class="clearly-footer-brand"><a class="clearly-footer-logo" href="index.html">Clearly<span>.</span></a><p class="clearly-footer-intro">Professional cleaning essentials for homes, hospitality teams and businesses—chosen to make every space cleaner and easier to care for.</p><div class="clearly-contact"><h2>Contact us</h2><div class="clearly-contact-item"><span>Phone number</span><strong>+91 97910 46050</strong></div><div class="clearly-contact-item"><span>Email address</span><strong>adhithyachem@gmail.com</strong></div><div class="clearly-contact-item"><span>Office location</span><strong>Chennai, Tamil Nadu</strong></div></div><div class="clearly-social" aria-label="Social links"><a href="#" aria-label="Facebook">f</a><a href="#" aria-label="Instagram">◎</a><a href="#" aria-label="LinkedIn">in</a><a href="#" aria-label="YouTube">▶</a></div><span class="clearly-currency">🇮🇳 <b>INR</b></span></section><section><h2>Discover</h2><a href="category.html?category=housekeeping-cleaning-supplies">Housekeeping &amp; cleaning</a><a href="category.html?category=tissue-paper-dispensers">Tissue paper &amp; dispensers</a><a href="category.html?category=swimming-pool-supplies">Swimming pool supplies</a><a href="category.html?category=construction-chemicals">Construction chemicals</a><a href="products.html">Best sellers</a><a href="products.html">New arrivals</a></section><section><h2>Help</h2><a href="mailto:adhithyachem@gmail.com">Contact us</a><a href="track-order.html">Track your order</a><a href="#">Shipping &amp; handling</a><a href="#">Returns &amp; exchanges</a><a href="#">Payment methods</a><a href="#">Frequently asked questions</a></section><section><h2>About Clearly</h2><a href="index.html#about">About us</a><a href="index.html#offers">Offers &amp; updates</a><a href="products.html">Our products</a><a href="account.html">My account</a></section><div class="clearly-footer-bottom"><span>© 2026 Clearly. All rights reserved.</span><span>Quality cleaning, delivered simply.</span></div>`;const oldFooter=document.querySelector('footer.store-footer,footer.site-footer');if(oldFooter)oldFooter.replaceWith(footer);else document.body.appendChild(footer);
  const footerContactLink=footer.querySelector('a[href="mailto:adhithyachem@gmail.com"]');if(footerContactLink)footerContactLink.href='contact.html';
  const helpLinks={
    'Shipping & handling':'shipping-handling.html',
    'Returns & exchanges':'returns-exchanges.html',
    'Payment methods':'payment-methods.html',
    'Frequently asked questions':'index.html#faq'
  };
  footer.querySelectorAll('a').forEach(link=>{const destination=helpLinks[link.textContent.trim()];if(destination)link.href=destination;});
  nav.querySelectorAll('a[href="index.html#about"]').forEach(link=>link.href='about.html');footer.querySelectorAll('a[href="index.html#about"]').forEach(link=>link.href='about.html');
  const reveal=()=>{nav.style.visibility='';overlay.style.visibility='';};stylesheet.onload=()=>document.head.appendChild(menuStyles);menuStyles.onload=reveal;document.head.appendChild(stylesheet);setTimeout(reveal,800);
  const lockDrawerWidth=()=>{const width=Math.max(0,window.innerWidth-document.documentElement.clientWidth);document.body.style.setProperty('--site-drawer-scrollbar',width+'px');};const close=()=>{overlay.classList.remove('open');document.body.classList.remove('site-drawer-open');document.body.style.removeProperty('--site-drawer-scrollbar');categoryButton.setAttribute('aria-expanded','false');};categoryButton.setAttribute('aria-expanded','false');categoryButton.onclick=()=>{lockDrawerWidth();overlay.classList.add('open');document.body.classList.add('site-drawer-open');categoryButton.setAttribute('aria-expanded','true');};overlay.onclick=e=>{if(e.target===overlay)close();};overlay.querySelector('#site-close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
  const categoryList=overlay.querySelector('#site-category-list');
  const renderCategories=items=>{categoryList.innerHTML=items.map((category,index)=>{const name=Array.isArray(category)?category[0]:category.name,slug=Array.isArray(category)?category[1]:category.slug,image=Array.isArray(category)?category[2]:(category.imageUrl||categoryImages[category.slug]||'assets/categories/floor-care-living-hall.png');return `<a class="site-category-item" style="--category-index:${Math.min(index,8)}" href="category.html?category=${encodeURIComponent(slug)}"><img src="${escapeHtml(image)}" alt=""><b>${escapeHtml(name)}</b><i>›</i></a>`;}).join('')||'<p class="site-category-empty">No categories are available right now.</p>';};
  renderCategories(fallbackCategories);
  fetch(categoryApi,{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('Categories unavailable');return response.json();}).then(rows=>renderCategories((rows||[]).filter(category=>category.enabled!==false).sort((a,b)=>Number(a.sortOrder||0)-Number(b.sortOrder||0)||String(a.name).localeCompare(String(b.name))))).catch(()=>{});
  fetch(homepageApi,{cache:'no-store'}).then(response=>response.ok?response.json():{}).then(settings=>applyThemeAccent(settings.themeAccent)).catch(()=>applyThemeAccent());
  const searchForm=nav.querySelector('.site-search'),searchInput=searchForm.querySelector('input'),searchResults=document.createElement('div');searchResults.className='site-search-results';searchResults.hidden=true;searchForm.appendChild(searchResults);
  const hideSearchResults=()=>{searchResults.hidden=true;searchResults.replaceChildren();};
  let remoteSearchProducts=[],searchLoad=null,searchSequence=0;const searchApi=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8080/api/products':'/api/products';
  const searchCatalogue=()=>{if(typeof PRODUCTS!=='undefined'&&PRODUCTS.length)return Promise.resolve(PRODUCTS);if(remoteSearchProducts.length)return Promise.resolve(remoteSearchProducts);if(!searchLoad)searchLoad=fetch(searchApi,{cache:'no-store'}).then(response=>response.ok?response.json():[]).then(rows=>{remoteSearchProducts=(rows||[]).map(product=>Object.assign({},product,{id:product.productCode||product.id,image:product.image||product.imageUrl||product.image_url||''}));return remoteSearchProducts;}).catch(()=>[]);return searchLoad;};
  const productMatches=(query,items)=>{const words=query.toLowerCase().split(/\s+/).filter(Boolean);return items.filter(product=>{const text=[product.name,product.brandName,product.brand,product.category,product.subcategory].filter(Boolean).join(' ').toLowerCase();return words.every(word=>text.includes(word));}).sort((a,b)=>{const aStarts=String(a.name||'').toLowerCase().startsWith(query.toLowerCase()),bStarts=String(b.name||'').toLowerCase().startsWith(query.toLowerCase());return Number(bStarts)-Number(aStarts)||String(a.name).localeCompare(String(b.name));}).slice(0,6);};
  const renderSearchResults=()=>{const query=searchInput.value.trim(),sequence=++searchSequence;if(query.length<1){hideSearchResults();return;}searchCatalogue().then(items=>{if(sequence!==searchSequence||searchInput.value.trim()!==query)return;const matches=productMatches(query,items);searchResults.replaceChildren();if(!matches.length){const empty=document.createElement('p');empty.className='site-search-empty';empty.textContent='No matching products';searchResults.appendChild(empty);}else matches.forEach(product=>{const row=document.createElement('a');row.className='site-search-result';row.href='product.html?id='+encodeURIComponent(product.id||product.productRef);const image=document.createElement('img');image.src=product.image||'assets/product-placeholder.png';image.alt='';const name=document.createElement('span');name.textContent=product.name;row.append(image,name);searchResults.appendChild(row);});searchResults.hidden=false;});};
  searchInput.addEventListener('input',renderSearchResults);searchInput.addEventListener('focus',renderSearchResults);window.addEventListener('clearly-catalog-loaded',renderSearchResults);document.addEventListener('pointerdown',event=>{if(!searchForm.contains(event.target))hideSearchResults();});document.addEventListener('keydown',event=>{if(event.key==='Escape')hideSearchResults();});
  searchForm.onsubmit=e=>{e.preventDefault();const q=searchInput.value.trim();const first=searchResults.querySelector('.site-search-result');if(q.length>=1&&first){location.href=first.href;return;}location.href='products.html'+(q?'?search='+encodeURIComponent(q):'');};
  const logout=nav.querySelector('#site-logout');if(logout)logout.onclick=()=>{const old=document.querySelector('#logout-button');if(old)old.click();else{sessionStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_profile');location.href='index.html';}};
  function counts(){let cart={},wish=[];try{cart=JSON.parse(sessionStorage.getItem('clearly_cart')||'{}')||{};wish=JSON.parse(localStorage.getItem('clearly_saved')||'[]')||[];}catch(error){}const cc=Object.values(cart).reduce((s,v)=>s+Number(v||0),0);nav.querySelector('[data-site-cart]').textContent=cc;nav.querySelector('[data-site-wish]').textContent=wish.length;}
  counts();window.addEventListener('clearly-shop-loaded',counts);window.addEventListener('clearly-cart-updated',counts);window.addEventListener('storage',counts);
})();
