(function(){
  'use strict';
  var base=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8085/api':'/api';
  var form=document.getElementById('tracking-form'),input=document.getElementById('tracking-order-id'),message=document.getElementById('tracking-message'),result=document.getElementById('tracking-result');
  function token(){return sessionStorage.getItem('clearly_access_token')||localStorage.getItem('clearly_access_token')||'';}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];});}
  function money(value,currency){return new Intl.NumberFormat('en-IN',{style:'currency',currency:currency||'INR'}).format(Number(value||0));}
  function stepCount(order){var payment=String(order.paymentStatus||''),status=String(order.orderStatus||'').toUpperCase();if(['DELIVERED','COMPLETED'].includes(status))return 4;if(['SHIPPED','OUT_FOR_DELIVERY'].includes(status))return 3;if(payment==='PAID'||['CONFIRMED','PROCESSING','PACKED'].includes(status))return 2;return 1;}
  function render(order){var active=stepCount(order),steps=['Order placed','Payment confirmed','Shipped','Delivered'],items=Array.isArray(order.items)?order.items:[];result.innerHTML='<div class="tracking-result-head"><div><small>ORDER ID</small><h2>'+esc(order.orderNo)+'</h2></div><span class="tracking-status">'+esc(String(order.orderStatus||'Processing').replace(/_/g,' '))+'</span></div><div class="tracking-timeline">'+steps.map(function(label,index){return '<div class="tracking-step '+(index<active?'done':'')+'">'+label+'</div>';}).join('')+'</div><div class="tracking-facts"><div><small>ORDER DATE</small><b>'+new Date(order.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})+'</b></div><div><small>DESTINATION</small><b>'+esc([order.destinationCity,order.destinationState].filter(Boolean).join(', '))+'</b></div><div><small>ORDER TOTAL</small><b>'+money(order.totalAmount,order.currency)+'</b></div></div><div class="tracking-items"><h3>'+Number(order.itemCount||0)+' item'+(Number(order.itemCount||0)===1?'':'s')+' in this order</h3><ul>'+items.map(function(item){return '<li><span>'+esc(item.productName)+'</span><b>Qty '+esc(item.quantity)+'</b></li>';}).join('')+'</ul></div>';result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'start'});}
  input.value=new URLSearchParams(location.search).get('orderId')||'';
  input.oninput=function(){this.value=this.value.toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,40);};
  form.onsubmit=function(event){event.preventDefault();var orderId=input.value.trim();message.textContent='';result.hidden=true;if(!orderId){message.textContent='Enter your Order ID.';input.focus();return;}if(!token()){if(window.ClearlyShop)window.ClearlyShop.requireSignIn('track your order','track-order.html?orderId='+encodeURIComponent(orderId));return;}var button=form.querySelector('button');button.disabled=true;button.textContent='Checking…';fetch(base+'/checkout/track?orderId='+encodeURIComponent(orderId),{headers:{Authorization:'Bearer '+token()},cache:'no-store'}).then(function(response){return response.json().catch(function(){return {};}).then(function(body){if(response.status===401||response.status===403){sessionStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_access_token');if(window.ClearlyShop)window.ClearlyShop.requireSignIn('track your order','track-order.html?orderId='+encodeURIComponent(orderId));throw new Error('');}if(!response.ok)throw new Error(body.detail||body.message||'We could not find that order.');return body;});}).then(render).catch(function(error){message.textContent=error.message;}).finally(function(){button.disabled=false;button.textContent='Track my order';});};
})();
