(function(){
  const products=typeof PRODUCTS!=='undefined'?PRODUCTS:[],grid=document.querySelector('#category-products'),rail=document.querySelector('#subcategory-rail'),brandSelect=document.querySelector('#category-brand'),params=new URLSearchParams(location.search),api=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8080/api/categories':'/api/categories';
  let tree=[],activeSlug=params.get('category')||'',activeLeaf=params.get('subcategory')||'all',activeBrand=params.get('brand')||'all',cart={},saved=[];
  try{cart=JSON.parse(sessionStorage.getItem('clearly_cart')||'{}')||{};saved=JSON.parse(localStorage.getItem('clearly_saved')||'[]')||[];}catch(error){}
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const current=()=>tree.find(x=>x.slug===activeSlug)||tree[0];
  const leaves=x=>(x.children&&x.children.length?x.children:[x]).filter(x=>x.enabled!==false);
  const allLeaves=()=>current()?(current().subcategories||[]).flatMap(leaves):[];
  function packages(p){const list=(p.packages||[]).filter(x=>x.enabled!==false);return list.length?list:(p.sizes||[p.packaging||'Standard pack']).map((label,i)=>({label,price:Number(p.price||0),originalPrice:Number(p.originalPrice||p.price||0),isDefault:i===0}));}
  function hero(){const c=current();if(!c)return;activeSlug=c.slug;document.title=c.name+' — Clearly.';document.querySelector('.category-hero-copy .category-eyebrow').textContent='SHOP CATEGORY';document.querySelector('.category-hero-copy h1').textContent=c.name;document.querySelector('.category-hero-copy > p').textContent=c.description||'Browse products by subcategory, brand and package size.';const img=document.querySelector('.category-hero-art img');img.src=c.imageUrl||'assets/categories/floor-care-living-hall.png';img.alt=c.name;}
  function filters(){const items=allLeaves();if(activeLeaf!=='all'&&!items.some(x=>x.slug===activeLeaf))activeLeaf='all';const allCard='<button class="subcategory '+(activeLeaf==='all'?'active':'')+'" data-leaf="all"><span class="subcategory-image all">◎</span><b>All products</b></button>';rail.innerHTML=allCard+items.map(x=>{const product=products.find(p=>p.category===x.name),image=product?.image||'assets/categories/floor-care-living-hall.png';return '<button class="subcategory '+(activeLeaf===x.slug?'active':'')+'" data-leaf="'+esc(x.slug)+'"><span class="subcategory-image"><img src="'+esc(image)+'" alt=""></span><b>'+esc(x.name)+'</b></button>';}).join('');const leafNames=items.map(x=>x.name),brands=[...new Set(products.filter(p=>leafNames.includes(p.category)).map(p=>p.brand))].sort();if(activeBrand!=='all'&&!brands.includes(activeBrand))activeBrand='all';brandSelect.innerHTML='<option value="all">All brands</option>'+brands.map(b=>'<option value="'+esc(b)+'">'+esc(b)+'</option>').join('');brandSelect.value=activeBrand;}
  function render(){hero();filters();const leafNames=allLeaves().map(x=>x.name),list=products.filter(p=>leafNames.includes(p.category)&&(activeLeaf==='all'||allLeaves().find(x=>x.slug===activeLeaf)?.name===p.category)&&(activeBrand==='all'||p.brand===activeBrand));document.querySelector('#category-count').textContent=list.length;document.querySelector('#category-result-count').textContent=list.length;document.querySelector('#category-filter-copy').textContent=activeLeaf==='all'?'across all subcategories':'in '+(allLeaves().find(x=>x.slug===activeLeaf)?.name||'selected group');grid.innerHTML=list.map(p=>{const list=packages(p),d=list.find(x=>x.isDefault)||list[0],href='product.html?id='+encodeURIComponent(p.id),old=d.originalPrice>d.price?'<span class="old">₹'+Number(d.originalPrice).toLocaleString('en-IN')+'</span>':'';return '<article class="product-card" data-id="'+esc(p.id)+'"><a class="product-img" href="'+href+'"><img src="'+esc(p.image)+'" alt="'+esc(p.name)+'"></a><div class="product-category">'+esc(p.category)+'</div><h3 class="product-name"><a href="'+href+'">'+esc(p.name)+'</a></h3><span class="product-stars">★★★★★ <small>('+Number(p.rating||0).toFixed(1)+')</small></span><div class="sizes"><select class="package-select" data-package aria-label="Choose package size"><option value="">Select package size</option>'+list.map((x,i)=>'<option value="'+i+'" data-size="'+esc(x.label)+'" data-price="'+Number(x.price||0)+'" data-mrp="'+Number(x.originalPrice||x.price||0)+'">'+esc(x.label)+'</option>').join('')+'</select></div><small class="size-prompt">Select a package size</small><div class="product-price">'+old+'<span class="now">₹'+Number(d.price).toLocaleString('en-IN')+'</span></div><div class="product-actions"><button class="cart-btn" data-cart="'+esc(p.id)+'">Add to bag</button><button class="wishlist-btn'+(saved.includes(p.id)?' on':'')+'" data-wish="'+esc(p.id)+'"><span class="ico">'+(saved.includes(p.id)?'♥':'♡')+'</span></button></div></article>';}).join('')||'<div class="category-empty"><h3>No matching products yet</h3><p>Try another subcategory or brand.</p></div>';}
  rail.addEventListener('click',e=>{const b=e.target.closest('[data-leaf]');if(b){activeLeaf=b.dataset.leaf;render();}});brandSelect.onchange=()=>{activeBrand=brandSelect.value;render();};document.querySelector('#category-clear').onclick=()=>{activeLeaf='all';activeBrand='all';render();};document.querySelector('#category-sort').onchange=render;
  grid.addEventListener('change',e=>{const s=e.target.closest('[data-package]');if(!s||!s.value)return;const o=s.options[s.selectedIndex],card=s.closest('.product-card'),price=Number(o.dataset.price),mrp=Number(o.dataset.mrp);card.querySelector('.size-prompt').textContent='Selected: '+o.dataset.size;card.querySelector('.product-price').innerHTML=(mrp>price?'<span class="old">₹'+mrp.toLocaleString('en-IN')+'</span>':'')+'<span class="now">₹'+price.toLocaleString('en-IN')+'</span>';});
  grid.addEventListener('click',e=>{const add=e.target.closest('[data-cart]');if(add){const card=add.closest('.product-card'),s=card.querySelector('[data-package]'),o=s.options[s.selectedIndex];if(!s.value){card.querySelector('.size-prompt').textContent='Please select a package size first';return;}const k=add.dataset.cart+'@@'+encodeURIComponent(o.dataset.size);cart[k]=Number(cart[k]||0)+1;sessionStorage.setItem('clearly_cart',JSON.stringify(cart));window.ClearlyShop?.saveCart(cart);add.textContent='Added ✓';setTimeout(()=>add.textContent='Add to bag',1000);return;}const wish=e.target.closest('[data-wish]');if(wish){const id=wish.dataset.wish;saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem('clearly_saved',JSON.stringify(saved));window.ClearlyShop?.saveWishlist(saved);render();}});
  fetch(api,{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(rows=>{tree=(rows||[]).filter(x=>x.enabled!==false).sort((a,b)=>Number(a.sortOrder||0)-Number(b.sortOrder||0));if(!tree.some(x=>x.slug===activeSlug))activeSlug=tree[0]?.slug||'';render();}).catch(render);window.addEventListener('clearly-catalog-loaded',render);
})();
