(function(){
  'use strict';
  const base=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8085/api':'/api';
  const token=sessionStorage.getItem('clearly_access_token')||localStorage.getItem('clearly_access_token');
  if(!token){location.replace('account.html');return;}
  const $=selector=>document.querySelector(selector), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state={companies:[],company:null,section:null,page:0};
  const sections={
    orders:{icon:'🛒',title:'Orders',copy:'Review your past and current orders.',columns:[['date','Date'],['number','Order no.'],['items','Items'],['amount','Amount'],['status','Status'],['download','Order PDF']]},
    shipments:{icon:'🚚',title:'Shipments',copy:'Track all your shipments in real time.',columns:[['date','Date'],['tracking','Tracking'],['carrier','Carrier'],['destination','Destination'],['status','Status'],['download','Shipment PDF']]},
    invoices:{icon:'▧',title:'Invoices',copy:'Access and download your invoices.',columns:[['date','Date'],['number','Invoice no.'],['items','Items'],['amount','Amount'],['status','Status'],['download','Invoice PDF']]},
    payments:{icon:'₹',title:'Payments',copy:'Review payments received and reconciled.',columns:[['date','Date'],['reference','Reference'],['amount','Amount'],['status','Status']]},
    ledger:{icon:'☷',title:'Ledger Statement',copy:'Track all credits, debits, and balances.',columns:[['date','Date'],['document','Document'],['debit','Debit'],['credit','Credit'],['balance','Balance'],['download','Statement PDF']]},
    addresses:{icon:'⌖',title:'Addresses',copy:'Manage addresses for billing and delivery.',columns:[['type','Type'],['address','Address'],['city','City'],['state','State'],['pincode','Pincode']]},
    contacts:{icon:'♙',title:'Contacts',copy:'Edit or add your company contact persons.',columns:[['name','Name'],['email','Email'],['phone','Phone'],['role','Role'],['phoneVerified','Phone verified']]}
  };
  async function api(path,options={}){const response=await fetch(base+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(options.headers||{})}}),body=await response.json().catch(()=>({}));if(response.status===401||response.status===403){clearSession();location.replace('account.html');throw new Error('Please sign in again');}if(!response.ok)throw new Error(body.detail||body.message||'Could not complete that request');return body;}
  function value(row,key){if(row[key]!==undefined)return row[key];const found=Object.keys(row).find(name=>name.toLowerCase()===key.toLowerCase());return found?row[found]:'';}
  function money(number){return '₹'+Number(number||0).toLocaleString('en-IN',{maximumFractionDigits:2});}
  function toast(copy){const el=$('#profile-toast');el.textContent=copy;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),1800);}
  function clearSession(){sessionStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_profile');sessionStorage.removeItem('clearly_cart');localStorage.removeItem('clearly_saved');}
  function localToday(){const now=new Date(),pad=value=>String(value).padStart(2,'0');return `${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}`;}
  function validateDates(){const from=$('#from-date').value,to=$('#to-date').value,warning=$('#date-warning'),today=localToday();let message='';if(to&&to>today){$('#to-date').value='';message='Future dates are not allowed. Please choose today or an earlier date.';}else if(from&&to&&from>to){message='The To date must be the same as or later than the From date.';}warning.textContent=message;warning.hidden=!message;return !message;}
  function show(view,scroll=true){['companies-view','company-view','table-view'].forEach(id=>$('#'+id).hidden=id!==view);if(scroll)scrollTo({top:0,behavior:'smooth'});}
  async function loadProfile(){const user=await api('/auth/me');$('#nav-user').textContent=user.name||user.email||user.phone||'My profile';}
  async function loadCompanies(){state.companies=await api('/profile/companies');renderCompanies();}
  function renderCompanies(){const list=$('#company-list');if(!state.companies.length){list.innerHTML='<div class="empty-state"><b>No companies yet</b>Add your first company to manage orders, addresses, and invoices.</div>';return;}list.innerHTML=state.companies.map(company=>`<button class="company-card" data-company="${company.id}"><span class="company-avatar">${esc(company.name.charAt(0))}</span><span class="company-copy"><strong>${esc(company.name)}</strong><span>${esc(company.city)}, ${esc(company.state)}${company.gstin?' · GSTIN '+esc(company.gstin):''}</span></span><span class="company-meta">${Number(company.orderCount||0)} orders<br>${money(company.orderValue||0)}</span><span class="company-arrow">›</span></button>`).join('');list.querySelectorAll('[data-company]').forEach(button=>button.onclick=()=>openCompany(Number(button.dataset.company)));}
  async function openCompany(id){state.company=await api('/profile/companies/'+id);$('#company-name').textContent=state.company.name;$('#company-location').textContent=`${state.company.city}, ${state.company.state}`;$('#company-menu').innerHTML=Object.entries(sections).map(([key,item])=>`<button class="menu-card" data-section="${key}"><span class="menu-icon">${item.icon}</span><span><strong>${item.title}</strong><small>${item.copy}</small></span><span>›</span></button>`).join('');$('#company-menu').querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>openSection(button.dataset.section));show('company-view');history.replaceState(null,'',`profile.html?company=${id}`);}
  async function openSection(section,page=0,preserveScroll=false){state.section=section;state.page=page;const config=sections[section];$('#table-company').textContent=state.company.name;$('#table-title').textContent=config.title;$('#table-subtitle').textContent=config.copy;$('#date-filter').hidden=['addresses','contacts'].includes(section);$('#date-warning').hidden=true;const add=$('#table-add');add.hidden=!['addresses','contacts'].includes(section);if(!add.hidden){add.textContent=section==='addresses'?'＋ Add address':'＋ Add contact';add.onclick=()=>openDrawer(section==='addresses'?'address':'contact');}show('table-view',!preserveScroll);history.replaceState(null,'',`profile.html?company=${state.company.id}&section=${section}`);await loadRows();}
  async function loadRows(){const from=$('#from-date').value,to=$('#to-date').value,params=new URLSearchParams({page:state.page,size:6,from,to}),data=await api(`/profile/companies/${state.company.id}/${state.section}?${params}`);renderRows(data);}
  function formatCell(key,raw){if(['amount','debit','credit','balance'].includes(key))return money(raw);if(key==='status')return `<span class="status">${esc(raw)}</span>`;if(key==='phoneVerified')return raw?'<span class="verified">✓ Verified</span>':'<span class="pending">Pending</span>';if(key==='date'&&raw)return new Date(raw+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});return esc(raw||'—');}
  function documentCell(row){return `<button class="document-download" data-document-id="${esc(value(row,'id'))}">⇩ Download</button>`;}
  async function downloadDocument(rowId){try{const response=await fetch(`${base}/profile/companies/${state.company.id}/${state.section}/${rowId}/document`,{headers:{Authorization:'Bearer '+token}});if(!response.ok)throw new Error('Could not generate this document');const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${state.section}-${rowId}.pdf`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}catch(error){toast(error.message);}}
  function renderRows(data){const config=sections[state.section],table=$('#business-table'),rows=data.rows||[];if(!rows.length)table.innerHTML=`<div class="table-empty"><b>No ${config.title.toLowerCase()} found</b><span>There are no items to display at this time.</span></div>`;else table.innerHTML=`<table><thead><tr>${config.columns.map(column=>`<th>${column[1]}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${config.columns.map(column=>`<td>${column[0]==='download'?documentCell(row):formatCell(column[0],value(row,column[0]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;table.querySelectorAll('[data-document-id]').forEach(button=>button.onclick=()=>downloadDocument(button.dataset.documentId));const pages=Number(data.pages||1),pagination=$('#pagination');pagination.innerHTML=`<span>Showing ${rows.length?state.page*6+1:0}-${state.page*6+rows.length} of ${data.total||0}</span><button id="previous-page" ${state.page===0?'disabled':''}>← Previous</button><b>${state.page+1} / ${pages}</b><button id="next-page" ${state.page>=pages-1?'disabled':''}>Next →</button>`;$('#previous-page').onclick=()=>{if(state.page>0)openSection(state.section,state.page-1,true);};$('#next-page').onclick=()=>{if(state.page<pages-1)openSection(state.section,state.page+1,true);};}
  function openDrawer(type){$('#drawer-title').textContent={company:'Add Company',address:'Add Address',contact:'Add Contact'}[type];['company','address','contact'].forEach(name=>$('#'+name+'-form').hidden=name!==type);$('#drawer-message').textContent='';$('#drawer-overlay').hidden=false;$('#profile-drawer').classList.add('open');$('#profile-drawer').setAttribute('aria-hidden','false');}
  function closeDrawer(){$('#drawer-overlay').hidden=true;$('#profile-drawer').classList.remove('open');$('#profile-drawer').setAttribute('aria-hidden','true');}
  function formData(form){return Object.fromEntries(new FormData(form).entries());}
  $('[data-open-drawer="company"]').onclick=()=>openDrawer('company');$('#close-drawer').onclick=closeDrawer;$('#drawer-overlay').onclick=closeDrawer;document.querySelectorAll('[data-close]').forEach(button=>button.onclick=closeDrawer);
  $('#company-form').onsubmit=async event=>{event.preventDefault();try{const company=await api('/profile/companies',{method:'POST',body:JSON.stringify(formData(event.currentTarget))});event.currentTarget.reset();closeDrawer();await loadCompanies();toast('Company added');openCompany(Number(company.id));}catch(error){$('#drawer-message').textContent=error.message;}};
  $('#address-form').onsubmit=async event=>{event.preventDefault();try{await api(`/profile/companies/${state.company.id}/addresses`,{method:'POST',body:JSON.stringify(formData(event.currentTarget))});event.currentTarget.reset();closeDrawer();toast('Address added');openSection('addresses');}catch(error){$('#drawer-message').textContent=error.message;}};
  $('#contact-form').onsubmit=async event=>{event.preventDefault();try{await api(`/profile/companies/${state.company.id}/contacts`,{method:'POST',body:JSON.stringify(formData(event.currentTarget))});event.currentTarget.reset();closeDrawer();toast('Contact added');openSection('contacts');}catch(error){$('#drawer-message').textContent=error.message;}};
  document.querySelectorAll('[data-back="companies"]').forEach(button=>button.onclick=()=>{show('companies-view');history.replaceState(null,'','profile.html');});document.querySelectorAll('[data-back="company"]').forEach(button=>button.onclick=()=>openCompany(state.company.id));
  const today=localToday();$('#from-date').max=today;$('#to-date').max=today;$('#to-date').onchange=validateDates;$('#from-date').onchange=validateDates;
  $('#date-filter').onsubmit=event=>{event.preventDefault();if(!validateDates())return;state.page=0;loadRows();};$('#reset-filter').onclick=()=>{$('#from-date').value='';$('#to-date').value='';$('#date-warning').hidden=true;state.page=0;loadRows();};
  $('#logout-button').onclick=async()=>{try{await fetch(base+'/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+token}});}catch(error){}clearSession();if(window.google&&google.accounts&&google.accounts.id)google.accounts.id.disableAutoSelect();location.replace('index.html');};
  Promise.all([loadProfile(),loadCompanies()]).then(async()=>{const params=new URLSearchParams(location.search),id=Number(params.get('company')),section=params.get('section');if(id&&state.companies.some(company=>Number(company.id)===id)){await openCompany(id);if(section&&sections[section])await openSection(section);}}).catch(error=>{$('#company-list').innerHTML=`<div class="empty-state"><b>Could not load your profile</b>${esc(error.message)}</div>`;});
})();
