(function(){
  'use strict';
  var apiBase=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8085/api/shop':'/api/shop';
  var loading=null, writeQueue=Promise.resolve(), cartRevision=0;
  function token(){return sessionStorage.getItem('clearly_access_token')||localStorage.getItem('clearly_access_token')||'';}
  function signedIn(){return !!token();}
  function readObject(key){try{var value=JSON.parse(sessionStorage.getItem(key)||'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}catch(error){return {};}}
  function readArray(key){try{var value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[];}catch(error){return [];}}
  function cache(state){sessionStorage.setItem('clearly_cart',JSON.stringify(state.cart||{}));localStorage.setItem('clearly_saved',JSON.stringify(state.wishlist||[]));window.dispatchEvent(new CustomEvent('clearly-shop-loaded',{detail:state}));return state;}
  function clearLocal(){sessionStorage.removeItem('clearly_cart');sessionStorage.removeItem('clearly_guest_cart');localStorage.removeItem('clearly_saved');}
  function request(path,options){var auth=token();return fetch(apiBase+path,Object.assign({},options||{},{headers:Object.assign({'Content-Type':'application/json',Authorization:'Bearer '+auth},options&&options.headers||{})})).then(function(response){return response.json().catch(function(){return {};}).then(function(body){if(response.status===401||response.status===403){sessionStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_access_token');localStorage.removeItem('clearly_profile');clearLocal();throw new Error('AUTH_REQUIRED');}if(!response.ok)throw new Error(body.detail||body.message||'Could not save shopping data');return body;});});}
  function requireSignIn(area,returnPage){if(signedIn())return true;clearLocal();location.href='account.html?required='+encodeURIComponent(area)+'&return='+encodeURIComponent(returnPage||location.pathname.split('/').pop()||'index.html');return false;}
  function cartItems(cart){return Object.keys(cart||{}).filter(function(key){return Number(cart[key])>0;}).map(function(key){return {productRef:key,quantity:Math.max(1,Math.floor(Number(cart[key])))};});}
  function saveCart(cart){cartRevision++;sessionStorage.setItem('clearly_cart',JSON.stringify(cart||{}));window.dispatchEvent(new CustomEvent('clearly-cart-updated',{detail:{cart:cart||{}}}));if(!signedIn()){sessionStorage.setItem('clearly_guest_cart',JSON.stringify(cart||{}));return Promise.resolve({cart:cart||{},temporary:true});}writeQueue=writeQueue.catch(function(){}).then(function(){return request('/cart',{method:'PUT',body:JSON.stringify({items:cartItems(cart)})});});return writeQueue;}
  function saveWishlist(refs){if(!signedIn())return Promise.reject(new Error('AUTH_REQUIRED'));var unique=Array.from(new Set(refs||[]));localStorage.setItem('clearly_saved',JSON.stringify(unique));writeQueue=writeQueue.catch(function(){}).then(function(){return request('/wishlist',{method:'PUT',body:JSON.stringify({productRefs:unique})});});return writeQueue;}
  function load(){if(!signedIn())return Promise.resolve({cart:readObject('clearly_cart'),wishlist:[]});if(loading)return loading;var loadRevision=cartRevision;loading=request('/state').then(function(state){var guestCart=readObject('clearly_guest_cart'),localWishlist=readArray('clearly_saved'),serverCart=state.cart||{},serverWishlist=state.wishlist||[],migrations=[];if(cartRevision!==loadRevision){serverCart=readObject('clearly_cart');migrations.push(saveCart(serverCart).then(function(){sessionStorage.removeItem('clearly_guest_cart');}));}else if(Object.keys(guestCart).length){Object.keys(guestCart).forEach(function(key){serverCart[key]=Math.max(0,Math.floor(Number(serverCart[key]||0)))+Math.max(1,Math.floor(Number(guestCart[key]||0)));});migrations.push(saveCart(serverCart).then(function(){sessionStorage.removeItem('clearly_guest_cart');}));}if(!serverWishlist.length&&localWishlist.length){serverWishlist=localWishlist;migrations.push(saveWishlist(serverWishlist));}return Promise.all(migrations).then(function(){return cache({cart:serverCart,wishlist:serverWishlist});});}).catch(function(error){if(error.message==='AUTH_REQUIRED')location.replace('account.html');else window.dispatchEvent(new CustomEvent('clearly-shop-error',{detail:error}));throw error;}).finally(function(){loading=null;});return loading;}
  window.ClearlyShop={signedIn:signedIn,requireSignIn:requireSignIn,load:load,saveCart:saveCart,saveWishlist:saveWishlist,clearLocal:clearLocal};
  if(signedIn())load();
})();
