spring.application.name=order-service
server.port=${SERVER_PORT:8083}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
info.app.name=Category Service
info.app.description=Microservice for managing product categories
info.app.version=1.0.9
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/clearly_store?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:password}

#configure rabbitMQ
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.host=localhost


#configure kafka
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.function.definition=consumeAck

# configs to send to rabbitMQ
#orderCreatedEvent-out-0 = bindings grp
spring.cloud.stream.bindings.orderCreatedEvent-out-0.destination=order.created
spring.cloud.stream.bindings.orderCreatedEvent-out-0.content-type=application/json
spring.cloud.stream.bindings.orderCreatedEvent-out-0.group=${spring.application.name}

spring.cloud.stream.bindings.consumeAck-in-0.destination=order.ack
spring.cloud.stream.bindings.consumeAck-in-0.content-type=application/json
spring.cloud.stream.bindings.consumeAck-in-0.group=${spring.application.name}

razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}
