spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/products/**,/api/catalog/**,/api/homepage/**
        - id: catalog-uploads
          uri: lb://catalog-service
          predicates:
            - Path=/api/uploads/**
        - id: catalog-taxonomy
          uri: lb://catalog-service
          predicates:
            - Path=/api/brands/**,/api/categories/**
        - id: catalog-product-assets
          uri: lb://catalog-service
          predicates:
            - Path=/api/images/**,/api/packages/**,/api/discounts/**,/api/documents/**,/api/products/*/images,/api/products/*/packages,/api/products/*/discounts,/api/products/*/documents
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**,/api/cart/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/profile/**,/api/shop/**,/api/checkout/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    circuitbreaker:
      resilience4j:
        enabled: true

  data:
    redis:
       host: localhost
       port: 6379

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s  # use 's' for seconds, not raw numbers
    instances:
      category-breaker:
        baseConfig: default
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
info:
  app:
    name: gateway-service
    description: "This is api gateway"
    version: "1.0"
