(function(){
  'use strict';
  var API=window.CLEARLY_API_BASE||'http://localhost:8080/api', AUTH_API=(location.protocol==='file:'||location.port==='4173')?'http://localhost:8085/api/auth':'/api/auth', products=[], editing=null, galleryImages=[], catalog={brands:{},categories:[],categoryTree:[],measurementUnits:[]}, userPage=0;
  var $=function(s){return document.querySelector(s);};
  var $$=function(s){return Array.from(document.querySelectorAll(s));};
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  var format=function(n){return '₹'+Number(n||0).toLocaleString('en-IN');};
  var categoryDefaultImages={
    'home-care-cleaning':'../assets/categories/floor-care-living-hall.png',
    'restaurant-food-service':'../assets/categories/restaurant-food-service.png',
    'healthcare-institutions':'../assets/categories/healthcare-institutions.png',
    'laundry-chemicals':'../assets/categories/laundry-chemicals.png',
    'swimming-pool-chemicals':'../assets/categories/swimming-pool-chemicals.png',
    'hotel-hospitality':'../assets/categories/hotel-hospitality.png',
    'specialty-chemicals':'../assets/categories/specialty-chemicals.png',
    'construction-chemicals':'../assets/categories/construction-chemicals.png'
  };
  var schema={
    products:['id','product_code','hsn_code','brand_id','category_id','subcategory_id','name','price','original_price','description','how_to_use','measure_and_dilute','image_url','bulk_discount_enabled','status','created_at','updated_at'],
    categories:['id','name','slug','description','image_url','sort_order','enabled'],
    subcategories:['id','category_id','name','slug','description','image_url','sort_order','enabled'],
    brand_categories:['brand_id','category_id','enabled'],
    measurement_units:['id','code','name','symbol','dimension','enabled'],
    product_images:['id','product_id','image_url','sort_order','alt_text'],
    product_packages:['id','product_id','label','quantity','unit_id','package_type','package_code','price','original_price','stock_quantity','is_default','enabled','sort_order'],
    bulk_discounts:['id','package_id','min_quantity','discount_percent','unit_price','enabled'],
    product_documents:['id','product_id','document_name','document_url','mime_type','document_type','sort_order','enabled'],
    product_specifications:['id','product_id','specification_name','specification_value','sort_order']
  };
  var schemaText='Loading the normalized schema from admin/mysql-schema.sql…';

  function adminToken(){return sessionStorage.getItem('clearly_admin_token')||'';}
  function adminHeaders(extra){return Object.assign({Authorization:'Bearer '+adminToken()},extra||{});}
  function finishAuthCheck(){document.body.classList.remove('auth-pending');document.body.removeAttribute('aria-busy');}
  function showAdmin(){ $('#admin-login').classList.add('hidden');$('#admin-shell').classList.remove('hidden');finishAuthCheck(); }
  function showLogin(message){$('#admin-shell').classList.add('hidden');$('#admin-login').classList.remove('hidden');$('#admin-login-message').textContent=message||'';finishAuthCheck();}
  function verifyAdmin(token){if(!token){showLogin();return Promise.resolve(false);}return fetch(AUTH_API+'/me',{headers:{Authorization:'Bearer '+token}}).then(function(response){if(!response.ok)throw new Error('Please sign in again');return response.json();}).then(function(user){if(user.role!=='ADMIN')throw new Error('This account does not have administrator access');showAdmin();return true;}).catch(function(error){sessionStorage.removeItem('clearly_admin_token');showLogin(error.message);return false;});}
  $('#admin-login-form').onsubmit=function(event){event.preventDefault();var button=event.currentTarget.querySelector('button'),identifier=$('#admin-identifier').value.trim();button.disabled=true;$('#admin-login-message').textContent='Checking access…';fetch(AUTH_API+'/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:identifier,password:$('#admin-password').value})}).then(function(response){return response.json().catch(function(){return {};}).then(function(body){if(!response.ok)throw new Error(body.detail||body.message||'Sign in failed');return body;});}).then(function(result){sessionStorage.setItem('clearly_admin_token',result.accessToken);return verifyAdmin(result.accessToken);}).catch(function(error){showLogin(error.message);}).finally(function(){button.disabled=false;});};
  $('#admin-logout').onclick=function(){sessionStorage.removeItem('clearly_admin_token');$('#admin-password').value='';showLogin('You have signed out safely.');};

  function showView(name){$$('.nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.view===name);});$$('.view').forEach(function(v){v.classList.toggle('active',v.id==='view-'+name);});if(name==='users')loadUsers();if(name==='homepage')loadHomepage();}
  $$('.nav-item').forEach(function(b){b.onclick=function(){showView(b.dataset.view);};});

  function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
  function saveCatalog(){return fetch(API+'/catalog',{method:'PUT',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify(catalog)}).then(function(r){if(!r.ok)throw new Error('Could not save catalogue');return r.json();}).then(function(data){catalog=data;renderCatalog();populateProductOptions();});}
  function renderCatalog(){
    $('#brand-list').innerHTML=Object.keys(catalog.brands).sort().map(function(key){return '<span class="catalog-chip">'+esc(catalog.brands[key])+' <small>'+esc(key)+'</small></span>';}).join('')||'<span class="muted">No brands yet.</span>';
    $('#category-list').innerHTML=(catalog.categoryTree||[]).slice().sort(function(a,b){return Number(a.sortOrder||0)-Number(b.sortOrder||0)||String(a.name).localeCompare(String(b.name));}).map(function(category,index){var image=category.imageUrl||categoryDefaultImages[category.slug],visual=image?'<img src="'+esc(image)+'" alt="">':'<span class="category-admin-placeholder" aria-hidden="true">'+esc((category.name||'?').charAt(0))+'</span>';return '<article class="category-admin-row"><span class="category-admin-index" aria-label="Category '+(index+1)+'">'+(index+1)+'</span>'+visual+'<div><b>'+esc(category.name)+'</b><small>'+esc(category.slug)+'</small></div><button class="icon-button" type="button" data-edit-category="'+category.id+'">Edit</button></article>';}).join('')||'<span class="muted">No categories yet.</span>';
    $$('[data-edit-category]').forEach(function(button){button.onclick=function(){var category=(catalog.categoryTree||[]).find(function(item){return String(item.id)===button.dataset.editCategory;});if(category)openCategoryEditor(category);};});
  }
  function populateSubcategoryOptions(selected){
    var categorySelect=$('#product-category'),subcategorySelect=$('#product-subcategory');
    var tree=(catalog.categoryTree||[]).find(function(item){return item.name===categorySelect.value||item.slug===categorySelect.value;});
    var options=tree&&tree.subcategories||[];
    subcategorySelect.innerHTML='<option value="">Select subcategory</option>'+options.map(function(item){return '<option value="'+esc(item.name)+'">'+esc(item.name)+'</option>';}).join('');
    if(selected&&options.some(function(item){return item.name===selected;}))subcategorySelect.value=selected;
  }
  function populateProductOptions(){
    var brandSelect=$('#product-brand'), currentBrand=brandSelect.value;brandSelect.innerHTML=Object.keys(catalog.brands).sort(function(a,b){return catalog.brands[a].localeCompare(catalog.brands[b]);}).map(function(key){return '<option value="'+esc(key)+'">'+esc(catalog.brands[key])+'</option>';}).join('');if(currentBrand&&catalog.brands[currentBrand])brandSelect.value=currentBrand;
    var categorySelect=$('#product-category'), currentCategory=categorySelect.value;categorySelect.innerHTML='<option value="">Select main category</option>'+(catalog.categoryTree||[]).map(function(item){return '<option value="'+esc(item.name)+'">'+esc(item.name)+'</option>';}).join('');if(currentCategory&&(catalog.categories||[]).includes(currentCategory))categorySelect.value=currentCategory;populateSubcategoryOptions();populateBrandFilter();
  }
  function populateBrandFilter(){var select=$('#brand-filter');if(!select)return;var current=select.value,keys=Object.keys(catalog.brands||{});products.forEach(function(product){var key=product.brand;if(key&&keys.indexOf(key)===-1)keys.push(key);});keys.sort(function(a,b){return String(catalog.brands[a]||a).localeCompare(String(catalog.brands[b]||b));});select.innerHTML='<option value="">All brands</option>'+keys.map(function(key){return '<option value="'+esc(key)+'">'+esc(catalog.brands[key]||key)+'</option>';}).join('');if(keys.indexOf(current)!==-1)select.value=current;}
  $('#product-category').onchange=function(){populateSubcategoryOptions();};
  $('#new-brand-key').oninput=function(){if(!this.value)$('#new-brand-key').value=slugify($('#new-brand-name').value);};
  $('#new-brand-name').onblur=function(){if(!$('#new-brand-key').value)$('#new-brand-key').value=slugify(this.value);};
  $('#brand-form').onsubmit=function(e){e.preventDefault();var name=$('#new-brand-name').value.trim(),key=slugify($('#new-brand-key').value||name);if(!name||!key)return;if(catalog.brands[key]){alert('That brand key already exists.');return;}fetch(API+'/brands',{method:'POST',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify({name:name,slug:key})}).then(function(r){if(!r.ok)throw new Error('Could not create brand');return r.json();}).then(function(){return fetch(API+'/catalog');}).then(function(r){return r.json();}).then(function(data){catalog=data;renderCatalog();populateProductOptions();$('#brand-form').reset();});};
  function resetCategoryForm(){$('#category-form').reset();$('#category-edit-id').value='';$('#category-image-status').textContent='Or upload from your folder';$('#category-save-status').textContent='';$('#category-editor-title').textContent='Add category';$('#category-submit').textContent='Save category';$('#delete-category').classList.add('hidden');}
  function closeCategoryEditor(){$('#category-backdrop').classList.add('hidden');$('#category-drawer').classList.remove('open');}
  function openCategoryEditor(category){resetCategoryForm();if(category){$('#category-edit-id').value=category.id;$('#new-category-name').value=category.name||'';$('#new-category-slug').value=category.slug||'';$('#new-category-image').value=category.imageUrl||'';$('#new-category-order').value=Number(category.sortOrder||0);$('#category-editor-title').textContent='Edit category';if(Number(category.productCount||0)===0)$('#delete-category').classList.remove('hidden');}$('#category-backdrop').classList.remove('hidden');$('#category-drawer').classList.add('open');setTimeout(function(){$('#new-category-name').focus();},100);}
  $('#new-category').onclick=function(){openCategoryEditor(null);};$('#close-category').onclick=closeCategoryEditor;$('#category-cancel').onclick=closeCategoryEditor;$('#category-backdrop').onclick=closeCategoryEditor;
  $('#new-category-name').oninput=function(){if(!$('#category-edit-id').value&&!$('#new-category-slug').value)$('#new-category-slug').value=slugify(this.value);};
  $('#category-image-file').onchange=function(){var input=this,file=input.files&&input.files[0],status=$('#category-image-status');if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)){status.textContent='Choose a PNG, JPG or WebP image.';input.value='';return;}if(file.size>5*1024*1024){status.textContent='Image is too large (maximum 5 MB).';input.value='';return;}input.disabled=true;status.textContent='Uploading image…';upload(file).then(function(data){if(!data.url)throw new Error('Upload completed without a file path.');$('#new-category-image').value=API+'/'+String(data.url).replace(/^\/+/, '');status.textContent='Image uploaded. Save category to publish it.';}).catch(function(error){status.textContent=error.message||'Image upload failed.';}).finally(function(){input.disabled=false;input.value='';});};
  $('#category-form').onsubmit=function(e){e.preventDefault();var id=$('#category-edit-id').value,name=$('#new-category-name').value.trim(),slug=slugify($('#new-category-slug').value||name);if(!name||!slug)return;if(!id&&(catalog.categoryTree||[]).some(function(item){return item.name.toLowerCase()===name.toLowerCase();})){alert('That category already exists.');return;}var payload={name:name,slug:slug,imageUrl:$('#new-category-image').value.trim()||null,sortOrder:Math.max(0,Math.trunc(Number($('#new-category-order').value||0))),enabled:true};$('#category-save-status').textContent='Saving…';fetch(API+'/categories'+(id?'/'+encodeURIComponent(id):''),{method:id?'PUT':'POST',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify(payload)}).then(function(r){if(!r.ok)throw new Error('Could not save category');return r.json();}).then(function(){return fetch(API+'/catalog');}).then(function(r){return r.json();}).then(function(data){catalog=data;renderCatalog();populateProductOptions();localStorage.setItem('clearly_catalog_revision',String(Date.now()));closeCategoryEditor();resetCategoryForm();}).catch(function(error){$('#category-save-status').textContent=error.message;});};
  $('#delete-category').onclick=function(){var id=$('#category-edit-id').value,category=(catalog.categoryTree||[]).find(function(item){return String(item.id)===String(id);});if(!category)return;if(Number(category.productCount||0)>0){$('#category-save-status').textContent='This category contains products and cannot be deleted.';return;}if(!window.confirm('Delete “'+category.name+'”? This cannot be undone.'))return;$('#category-save-status').textContent='Deleting…';fetch(API+'/categories/'+encodeURIComponent(id),{method:'DELETE',headers:adminHeaders()}).then(function(r){if(!r.ok)throw new Error('Could not delete category');return fetch(API+'/catalog');}).then(function(r){return r.json();}).then(function(data){catalog=data;renderCatalog();populateProductOptions();localStorage.setItem('clearly_catalog_revision',String(Date.now()));closeCategoryEditor();resetCategoryForm();}).catch(function(error){$('#category-save-status').textContent=error.message;});};

  function loadProducts(){return fetch(API+'/products').then(function(r){if(!r.ok)throw new Error('Could not load products');return r.json();}).then(function(data){products=data||[];populateBrandFilter();renderProducts();});}
  function renderProducts(){
    var q=($('#product-search').value||'').toLowerCase(),brand=$('#brand-filter').value;var list=products.filter(function(p){var matchesBrand=!brand||p.brand===brand||p.subBrand===brand;return matchesBrand&&(!q||(p.name+' '+p.brand+' '+p.subBrand+' '+p.category).toLowerCase().includes(q));});
    $('#stat-total').textContent=products.length;$('#stat-images').textContent=products.filter(function(p){return p.image;}).length;$('#stat-bulk').textContent=products.filter(function(p){return p.bulkDiscountEnabled!==false&&(p.bulkDiscounts||[]).length>1;}).length;
    if(!list.length){$('#products-table').innerHTML='<div class="empty">No products found.</div>';return;}
    $('#products-table').innerHTML='<table class="catalog-table"><thead><tr><th>Product</th><th>HSN code</th><th>Brand</th><th>Package prices</th><th>Bulk table</th><th>Status</th><th></th></tr></thead><tbody>'+list.map(function(p){var packs=(p.packages||[]).filter(function(x){return x.enabled!==false;}),prices=packs.map(function(x){return Number(x.price||0);}),priceCopy=prices.length?(format(Math.min.apply(Math,prices))+(prices.length>1?' – '+format(Math.max.apply(Math,prices)):'')+'<small class="package-count">'+prices.length+' package'+(prices.length===1?'':'s')+'</small>'):format(p.price),productRef=p.productCode||p.product_code||p.id;return '<tr><td><div class="catalog-product">'+(p.image?'<img src="../'+esc(p.image.replace(/^\//,''))+'" alt="">':'<span class="catalog-placeholder">No image</span>')+'<div><b>'+esc(p.name)+'</b><small>'+esc(p.category||'Uncategorised')+'</small></div></div></td><td>'+esc(p.hsnCode||p.hsn_code||'—')+'</td><td>'+esc(p.subBrand||p.brand||'—')+'</td><td>'+priceCopy+'</td><td>'+(p.bulkDiscountEnabled!==false&&(p.bulkDiscounts||[]).length>1?'<span class="status-pill">Enabled</span>':'<span class="status-pill off">Disabled</span>')+'</td><td>'+(p.inStock===false?'<span class="status-pill off">Out of stock</span>':'<span class="status-pill">Active</span>')+'</td><td><div class="row-actions"><button class="icon-button" data-edit="'+esc(p.id)+'">Edit</button><a class="icon-button" href="../product.html?id='+encodeURIComponent(productRef)+'" target="_blank">View</a></div></td></tr>';}).join('')+'</tbody></table>';
    $$('[data-edit]').forEach(function(b){b.onclick=function(){fetch(API+'/products/'+encodeURIComponent(b.dataset.edit)).then(function(r){return r.json();}).then(openEditor);};});
  }
  $('#product-search').oninput=renderProducts;
  $('#brand-filter').onchange=renderProducts;

  function authToken(){return adminToken();}
  function dateLabel(value){if(!value)return 'Never';var date=new Date(value);return Number.isNaN(date.getTime())?'—':date.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});}
  function userAccessMessage(title,copy){
    $('#users-table').innerHTML='<div class="access-panel"><svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg><h3>'+esc(title)+'</h3><p>'+esc(copy)+'</p><a class="primary" href="../account.html">Sign in to Clearly</a></div>';
    $('#user-pagination').innerHTML='';
  }
  function loadUsers(){
    var token=authToken(), search=$('#user-search').value.trim();
    if(!token){userAccessMessage('Administrator sign-in required','Sign in with an account whose role is ADMIN to view registered users.');return;}
    $('#users-table').innerHTML='<div class="loading">Loading users…</div>';
    fetch(AUTH_API+'/admin/users?search='+encodeURIComponent(search)+'&page='+userPage+'&size=50',{headers:{Authorization:'Bearer '+token}}).then(function(r){
      if(r.status===401||r.status===403)throw new Error('ADMIN_REQUIRED');if(!r.ok)throw new Error('Could not load users');return r.json();
    }).then(renderUsers).catch(function(error){if(error.message==='ADMIN_REQUIRED')userAccessMessage('Administrator access required','Your account is signed in, but it does not have permission to view customer records.');else $('#users-table').innerHTML='<div class="empty">'+esc(error.message)+'</div>';});
  }
  function renderUsers(data){
    var users=data.users||[],summary=data.summary||{};
    $('#stat-users').textContent=summary.registered||0;$('#stat-verified').textContent=summary.verified||0;$('#stat-google').textContent=summary.google||0;
    if(!users.length){$('#users-table').innerHTML='<div class="empty">No users found.</div>';$('#user-pagination').innerHTML='';return;}
    $('#users-table').innerHTML='<table class="catalog-table"><thead><tr><th>User</th><th>Phone</th><th>Provider</th><th>Verification</th><th>Role</th><th>Status</th><th>Joined</th><th>Last login</th></tr></thead><tbody>'+users.map(function(user){var provider=String(user.provider||'LOCAL');return '<tr><td><div class="user-identity"><span class="user-avatar">'+esc((user.name||user.email||user.phone||'U').charAt(0).toUpperCase())+'</span><div><b>'+esc(user.name||'Unnamed user')+'</b><small>'+esc(user.email||'No email supplied')+'</small></div></div></td><td><b>'+esc(user.phone||'—')+'</b><small class="phone-state">'+(user.phone?(user.phoneVerified?'✓ Verified':'Pending verification'):'Not supplied')+'</small></td><td><span class="provider-pill '+(provider.includes('GOOGLE')?'google':'')+'">'+esc(provider.replace('_',' + '))+'</span></td><td>'+(user.emailVerified?'<span class="status-pill">Email</span>':'')+(user.phoneVerified?'<span class="status-pill phone">Phone</span>':'')+(!user.emailVerified&&!user.phoneVerified?'<span class="status-pill off">Pending</span>':'')+'</td><td><span class="role-pill '+(user.role==='ADMIN'?'admin':'')+'">'+esc(user.role||'CUSTOMER')+'</span></td><td>'+(user.status==='ACTIVE'?'<span class="status-pill">Active</span>':'<span class="status-pill off">'+esc(user.status)+'</span>')+'</td><td class="date-cell">'+dateLabel(user.createdAt)+'</td><td class="date-cell">'+dateLabel(user.lastLoginAt)+'</td></tr>';}).join('')+'</tbody></table>';
    var pages=Number(data.pages||1);$('#user-pagination').innerHTML='<span>Page '+(userPage+1)+' of '+Math.max(1,pages)+' · '+Number(data.total||0)+' users</span><button id="users-prev" '+(userPage<=0?'disabled':'')+'>← Previous</button><button id="users-next" '+(userPage>=pages-1?'disabled':'')+'>Next →</button>';
    $('#users-prev').onclick=function(){if(userPage>0){userPage--;loadUsers();}};$('#users-next').onclick=function(){if(userPage<pages-1){userPage++;loadUsers();}};
  }
  var userSearchTimer;$('#user-search').oninput=function(){clearTimeout(userSearchTimer);userPage=0;userSearchTimer=setTimeout(loadUsers,250);};$('#refresh-users').onclick=loadUsers;

  function tierMarkup(tier,i,total){var minimum=Math.max(1,Math.trunc(Number(tier.minQty||tier.minQuantity||1))),discount=Math.max(0,Math.min(100,Math.round(Number(tier.discountPct!=null?tier.discountPct:(tier.discountPercent||0)))));return '<div class="discount-tier" data-tier="'+i+'"><label>Minimum packages<input class="tier-qty" type="number" min="1" step="1" inputmode="numeric" value="'+minimum+'"></label><label>Discount %<input class="tier-pct" type="number" min="0" max="100" step="1" inputmode="numeric" value="'+discount+'"></label>'+(total>1?'<button type="button" class="remove-tier" data-remove-tier="'+i+'">×</button>':'<span></span>')+'</div>';}
  function renderTiers(tiers){var base=Number($('#product-price').value||0);tiers=tiers&&tiers.length?tiers:[{minQty:1,discountPct:0}];$('#discount-tiers').innerHTML=tiers.map(function(t,i){return tierMarkup(t,i,tiers.length);}).join('');$$('[data-remove-tier]').forEach(function(b){b.onclick=function(){b.parentElement.remove();};});}
  function unitOptions(selected){var units=(catalog.measurementUnits||[]);if(!units.length)units=[{code:'ML',symbol:'ml'},{code:'L',symbol:'L'},{code:'MG',symbol:'mg'},{code:'G',symbol:'g'},{code:'KG',symbol:'kg'},{code:'UNIT',symbol:'unit'}];return units.map(function(unit){var code=unit.code||unit.symbol;return '<option value="'+esc(code)+'" '+(String(selected||'').toUpperCase()===String(code).toUpperCase()?'selected':'')+'>'+esc(unit.symbol||unit.code)+'</option>';}).join('');}
  function packageMarkup(item,index,total){item=item||{};var mrp=Number(item.originalPrice||item.mrp||item.price||0),price=Number(item.price||0),discount=mrp>0?Math.max(0,Math.round((1-price/mrp)*10000)/100):0;var quantity=item.quantity||String(item.label||'').match(/[\d.]+/)?.[0]||1;return '<div class="package-row" data-package-id="'+esc(item.id||'')+'"><label><input class="package-qty" type="number" min="0.001" step="0.001" value="'+esc(quantity)+'" required></label><label><select class="package-unit">'+unitOptions(item.unit||item.symbol||'L')+'</select></label><label><input class="package-mrp" type="number" min="0" step="0.01" value="'+esc(mrp)+'" required></label><label><input class="package-discount" type="number" min="0" max="100" step="0.01" value="'+esc(discount)+'"></label><label><input class="package-price" type="number" min="0" step="0.01" value="'+esc(price)+'" readonly></label><label><input class="package-stock" type="number" min="0" step="1" value="'+esc(item.stockQuantity||0)+'"></label><label class="package-default"><input type="radio" name="default-package" '+(item.isDefault||index===0?'checked':'')+' aria-label="Default package"></label>'+(total>1?'<button class="remove-package" type="button" aria-label="Remove package">×</button>':'<span></span>')+'</div>';}
  function recalculatePackage(row){var mrp=Number(row.querySelector('.package-mrp').value||0),discount=Math.min(100,Math.max(0,Number(row.querySelector('.package-discount').value||0)));row.querySelector('.package-price').value=(mrp*(1-discount/100)).toFixed(2);}
  function bindPackageRows(){$$('.package-row').forEach(function(row){row.querySelector('.package-mrp').oninput=function(){recalculatePackage(row);};row.querySelector('.package-discount').oninput=function(){recalculatePackage(row);};var remove=row.querySelector('.remove-package');if(remove)remove.onclick=function(){row.remove();if(!document.querySelector('input[name="default-package"]:checked'))document.querySelector('input[name="default-package"]')?.click();};});}
  function renderPackages(items){items=items&&items.length?items:[{quantity:1,unit:'L',price:0,originalPrice:0,isDefault:true}];$('#package-rows').innerHTML=items.map(function(item,index){return packageMarkup(item,index,items.length);}).join('');bindPackageRows();}
  function readPackages(){return $$('.package-row').map(function(row,index){var quantity=Number(row.querySelector('.package-qty').value),unit=row.querySelector('.package-unit').value,mrp=Number(row.querySelector('.package-mrp').value),discount=Number(row.querySelector('.package-discount').value||0),price=Number((mrp*(1-discount/100)).toFixed(2));return {id:row.dataset.packageId||null,quantity:quantity,unit:unit,label:quantity+' '+((catalog.measurementUnits||[]).find(function(x){return x.code===unit;})||{symbol:unit}).symbol,originalPrice:mrp,discountPercent:discount,price:price,stockQuantity:Number(row.querySelector('.package-stock').value||0),isDefault:row.querySelector('input[type="radio"]').checked,enabled:true,sortOrder:index};});}
  $('#add-package').onclick=function(){var items=readPackages();items.push({quantity:1,unit:'L',price:0,originalPrice:0,isDefault:false});renderPackages(items);};
  function defaultGallery(p){
    var n=(p&&p.name||'').toLowerCase(), base=p&&p.image?[p.image]:[];
    var map={
      'nitotile grout':['assets/nitotile-grout-pack.png','assets/nitotile-grout-purpose.png'],
      'nitobond ep':['assets/nitobond-ep-new.png','assets/nitobond-ep-packaging-change.png','assets/nitobond-ep-how-to-use.png'],
      'brushbond rfx':['assets/brushbond-rfx-pack.png','assets/brushbond-rfx-pack-enhanced.png','assets/brushbond-rfx-how-to-use.png'],
      'conbextra gp2':['assets/conbextra-gp2-pack.png','assets/conbextra-gp2-how-to.png'],
      'auramix 500':['assets/auramix-500-barrel.png','assets/auramix-500-how-to.png'],
      'brushbond roofguard':['assets/brushbond-roofguard-studio.png','assets/brushbond-roofguard-how-to.png','assets/brushbond-roofguard-benefits.png'],
      'brushbond aquaprotect':['assets/brushbond-aquaprotect-studio.png','assets/brushbond-aquaprotect-info.png','assets/brushbond-aquaprotect-how-to.png','assets/brushbond-aquaprotect-benefits.png'],
      'conplast sp430':['assets/conplast-sp430-studio.png','assets/conplast-sp430-benefits.png','assets/conplast-sp430-site.png','assets/conplast-sp430-how-to.png'],
      'lokfix p':['assets/lokfix-p-enhanced.png','assets/lokfix-p-benefits.png','assets/lokfix-p-how-to.png'],
      'nitobond sbr latex':['assets/nitobond-sbr-studio.png','assets/nitobond-sbr-benefits.png','assets/nitobond-sbr-how-to.png']
    };
    var exact=map[n];
    if(exact)return exact;
    var taski=n.match(/^taski\s+r(1|2|3|4|5|6|7|9)/);
    if(taski){var code='r'+taski[1];return ['assets/taski/'+code+'-studio.png','assets/taski/'+code+'-benefits.png','assets/taski/'+code+'-howto.png','assets/taski/'+code+'-source.webp'];}
    return base;
  }
  function openEditor(p){
    editing=p||null;galleryImages=p&&p.images&&p.images.length?p.images.map(function(x){return x.imageUrl||x.image||x;}):defaultGallery(p);$('#editor-title').textContent=p?'Edit product':'New product';$('#product-id').value=p?p.id:'';$('#product-name').value=p?p.name:'';$('#product-hsn').value=p?p.hsnCode||p.hsn_code||'':'';$('#product-brand').value=p?p.brand:'fosroc';$('#product-category').value=p?p.category:'';populateSubcategoryOptions(p&&p.subcategory);var fallbackPackages=p&&!(p.packages||[]).length?(p.sizes||[]).map(function(size,index){return {label:size,price:p.price,originalPrice:p.originalPrice||p.price,isDefault:index===0};}):[];renderPackages(p&&(p.packages&&p.packages.length?p.packages:fallbackPackages));$('#product-price').value=p?p.price:'';$('#product-original').value=p?p.originalPrice||'':'';$('#product-description').value=p?p.description||p.use||'':'';$('#product-howto').value=p?p.measureAndDilute||p.measureDilute||p.howToUse||'':'';$('#product-image').value=galleryImages[0]||'';$('#document-url').value=p?p.documentUrl||'':'';$('#document-name').value=p?p.documentName||'':'';$('#document-status').textContent=p&&p.documentName?p.documentName:'No document selected';$('#bulk-enabled').checked=!!(p&&p.bulkDiscountEnabled!==false&&(p.bulkDiscounts||[]).length>1);renderTiers(p&&p.bulkDiscounts||[{minQty:1,discountPct:0}]);renderImagePreview();$('#save-status').textContent='';$('#drawer-backdrop').classList.remove('hidden');$('#editor-drawer').classList.add('open');}
  function closeEditor(){$('#drawer-backdrop').classList.add('hidden');$('#editor-drawer').classList.remove('open');editing=null;}
  $('#new-product').onclick=function(){openEditor(null);};$('#close-editor').onclick=closeEditor;$('#cancel-editor').onclick=closeEditor;$('#drawer-backdrop').onclick=closeEditor;
  $('#add-tier').onclick=function(){var tiers=readTiers();tiers.push({minQty:(tiers[tiers.length-1].minQty||1)*2,discountPct:5});renderTiers(tiers);};
  function readTiers(){return $$('.discount-tier').map(function(row){var input=row.querySelector('.tier-qty'),discountInput=row.querySelector('.tier-pct'),minimum=Math.max(1,Math.trunc(Number(input.value||1))),discount=Math.max(0,Math.min(100,Math.round(Number(discountInput.value||0))));input.value=minimum;discountInput.value=discount;return {minQty:minimum,discountPct:discount};});}
  function upload(file){var body=new FormData();body.append('file',file);return fetch(API+'/uploads',{method:'POST',headers:adminHeaders(),body:body}).then(function(r){return r.json().then(function(data){if(!r.ok)throw new Error(data.error||'Upload failed');return data;});});}
  function normalizeProductImage(file){return new Promise(function(resolve,reject){var source=URL.createObjectURL(file),image=new Image();image.onload=function(){var canvas=document.createElement('canvas'),size=1600,inner=1480,scale=Math.min(inner/image.naturalWidth,inner/image.naturalHeight),width=Math.max(1,Math.round(image.naturalWidth*scale)),height=Math.max(1,Math.round(image.naturalHeight*scale)),context=canvas.getContext('2d');canvas.width=size;canvas.height=size;context.fillStyle='#ffffff';context.fillRect(0,0,size,size);context.drawImage(image,(size-width)/2,(size-height)/2,width,height);URL.revokeObjectURL(source);canvas.toBlob(function(blob){if(!blob){reject(new Error('Could not prepare this image.'));return;}resolve(new File([blob],file.name.replace(/\.[^.]+$/,'')+'.jpg',{type:'image/jpeg'}));},'image/jpeg',.9);};image.onerror=function(){URL.revokeObjectURL(source);reject(new Error('Choose a valid PNG, JPG or WebP image.'));};image.src=source;});}
  function renderImagePreview(){
    $('#image-preview').innerHTML=galleryImages.map(function(url,i){return '<div class="gallery-image"><img src="../'+esc(url.replace(/^\//,''))+'" alt="Carousel image '+(i+1)+'"><button type="button" data-remove-image="'+i+'">×</button><small>'+(i===0?'Main image':'Carousel image '+(i+1))+'</small></div>';}).join('');
    $$('[data-remove-image]').forEach(function(b){b.onclick=function(){galleryImages.splice(Number(b.dataset.removeImage),1);$('#product-image').value=galleryImages[0]||'';renderImagePreview();};});
  }
  $('#image-file').onchange=function(){var files=Array.from(this.files||[]);if(!files.length)return;Promise.all(files.map(normalizeProductImage).map(function(work){return work.then(upload);})).then(function(results){results.forEach(function(data){galleryImages.push(data.url);});$('#product-image').value=galleryImages[0]||'';renderImagePreview();}).catch(function(e){alert(e.message);});this.value='';};
  $('#document-file').onchange=function(){var file=this.files[0];if(!file)return;$('#document-status').textContent='Uploading…';upload(file).then(function(data){$('#document-url').value=data.url;$('#document-name').value=file.name;$('#document-status').textContent=file.name;}).catch(function(e){$('#document-status').textContent=e.message;});};
  $('#product-image').oninput=function(){if(this.value&&!galleryImages.length)galleryImages=[this.value];else if(this.value&&galleryImages.length)galleryImages[0]=this.value;renderImagePreview();};
  function syncBulkDiscounts(productRef,enabled,tiers){return fetch(API+'/products/'+encodeURIComponent(productRef),{headers:adminHeaders()}).then(function(response){if(!response.ok)throw new Error('Could not load saved packages for quantity discounts');return response.json();}).then(function(product){var discounts=product.bulkDiscounts||[],packages=(product.packages||[]).filter(function(item){return item.enabled!==false;}),target=packages.find(function(item){return item.isDefault||item.is_default;})||packages[0];if(!target)throw new Error('Create a package size before saving quantity discounts.');return Promise.all(discounts.map(function(discount){return fetch(API+'/discounts/'+encodeURIComponent(discount.id),{method:'DELETE',headers:adminHeaders()}).then(function(response){if(!response.ok)throw new Error('Could not replace the existing quantity discounts');});})).then(function(){if(!enabled)return [];return Promise.all(tiers.sort(function(a,b){return a.minQty-b.minQty;}).map(function(tier){var percent=Math.max(0,Math.min(100,Math.round(Number(tier.discountPct||0)))),unitPrice=Number((Number(target.price||0)*(1-percent/100)).toFixed(2));return fetch(API+'/products/'+encodeURIComponent(productRef)+'/discounts',{method:'POST',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify({packageId:target.id,minQuantity:Math.max(1,Math.trunc(Number(tier.minQty||1))),discountPercent:percent,unitPrice:unitPrice,enabled:true})}).then(function(response){if(!response.ok)throw new Error('Could not save a quantity discount tier');return response.json();});}));});});}
  $('#product-form').onsubmit=function(e){
    e.preventDefault();var packages=readPackages();if(!packages.length){$('#save-status').textContent='Add at least one package size.';return;}var defaultPackage=packages.find(function(x){return x.isDefault;})||packages[0],tiers=readTiers().sort(function(a,b){return a.minQty-b.minQty;});var price=defaultPackage.price;var images=galleryImages.slice();if($('#product-image').value.trim()&&!images.length)images=[$('#product-image').value.trim()];var payload={brand:$('#product-brand').value,name:$('#product-name').value.trim(),hsnCode:$('#product-hsn').value.trim(),category:$('#product-category').value.trim(),subcategory:$('#product-subcategory').value.trim(),price:price,originalPrice:defaultPackage.originalPrice||undefined,image:images[0]||'',images:images,description:$('#product-description').value.trim(),use:$('#product-description').value.trim(),measureAndDilute:$('#product-howto').value.trim(),howToUse:$('#product-howto').value.trim(),documentUrl:$('#document-url').value,documentName:$('#document-name').value,bulkDiscountEnabled:$('#bulk-enabled').checked,bulkDiscounts:tiers.map(function(t){return {minQty:t.minQty,discountPercent:t.discountPct,unitPrice:Math.round(price*(1-t.discountPct/100))};})};
    var method=editing?'PUT':'POST',url=editing?API+'/products/'+encodeURIComponent(editing.id):API+'/products';$('#save-status').textContent='Saving product, packages and quantity discounts…';fetch(url,{method:method,headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify(payload)}).then(function(r){return r.json().then(function(data){if(!r.ok)throw new Error(data.error||'Save failed');return data;});}).then(function(saved){var ref=saved.productCode||saved.product_code||saved.id,existing=(editing&&editing.packages||[]).map(function(x){return String(x.id);}),kept=packages.filter(function(x){return x.id;}).map(function(x){return String(x.id);});var requests=packages.map(function(pkg){var target=pkg.id?API+'/packages/'+pkg.id:API+'/products/'+encodeURIComponent(ref)+'/packages';return fetch(target,{method:pkg.id?'PUT':'POST',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify(pkg)}).then(function(r){if(!r.ok)throw new Error('Could not save package '+pkg.label);return r.json();});});existing.filter(function(id){return !kept.includes(id);}).forEach(function(id){requests.push(fetch(API+'/packages/'+id,{method:'DELETE',headers:adminHeaders()}).then(function(r){if(!r.ok)throw new Error('Could not remove package');return {deleted:id};}));});return Promise.all(requests).then(function(){return syncBulkDiscounts(ref,$('#bulk-enabled').checked,tiers);});}).then(function(){localStorage.setItem('clearly_catalog_revision',String(Date.now()));closeEditor();return loadProducts();}).catch(function(e){$('#save-status').textContent=e.message;});
  };
  function renderSchema(){ $('#schema-cards').innerHTML=Object.keys(schema).map(function(name){return '<article class="schema-card"><h3>'+name+'</h3><p>MySQL table for '+name.replace(/_/g,' ')+' management.</p><ul>'+schema[name].map(function(col){return '<li>'+col+'</li>';}).join('')+'</ul></article>';}).join('');$('#schema-preview').textContent=schemaText; }
  $('#copy-schema').onclick=function(){navigator.clipboard.writeText(schemaText).then(function(){$('#copy-schema').textContent='Copied';setTimeout(function(){$('#copy-schema').textContent='Copy SQL';},1400);});};
  function homepageFields(){return Array.from($('#homepage-form').elements).filter(function(field){return field.name;});}
  var homepagePresets=[{name:'Clean studio',value:'assets/homepage/hero-clean-studio.png',preview:'/assets/homepage/hero-clean-studio.png'},{name:'Sunlit home',value:'assets/homepage/hero-sunlit-home.png',preview:'/assets/homepage/hero-sunlit-home.png'},{name:'Eco fresh',value:'assets/homepage/hero-eco-fresh.png',preview:'/assets/homepage/hero-eco-fresh.png'}];
  function normalizedHomepageImage(value){try{return new URL(value,location.href).pathname;}catch(error){return value||'';}}
  function updateHomepagePresetSelection(){var current=normalizedHomepageImage($('#homepage-form [name="heroImage"]').value);Array.from(document.querySelectorAll('.homepage-preset')).forEach(function(button){button.classList.toggle('selected',normalizedHomepageImage(button.dataset.value)===current);});}
  function renderHomepagePresets(){var grid=$('#homepage-preset-grid');grid.innerHTML=homepagePresets.map(function(preset){return '<button class="homepage-preset" type="button" data-value="'+preset.value+'" data-preview="'+preset.preview+'"><img src="'+preset.preview+'" alt="'+preset.name+' hero preview" /><strong>'+preset.name+'</strong></button>';}).join('');grid.onclick=function(event){var button=event.target.closest('.homepage-preset');if(!button)return;$('#homepage-form [name="heroImage"]').value=button.dataset.value;updateHomepagePresetSelection();$('#homepage-status').textContent='Preset selected. Save the home page to publish it.';};updateHomepagePresetSelection();}
  function uploadHomepageImage(input,fieldName){var file=input.files&&input.files[0],status=$('#homepage-status');if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)){status.textContent='Choose a PNG, JPG or WebP image.';input.value='';return;}if(file.size>5*1024*1024){status.textContent='Image is too large. Choose an image under 5 MB.';input.value='';return;}var body=new FormData();body.append('file',file);status.textContent='Uploading image…';input.disabled=true;fetch(API+'/uploads',{method:'POST',headers:adminHeaders(),body:body}).then(function(r){return r.text().then(function(text){var data={};if(text){try{data=JSON.parse(text);}catch(error){if(r.ok)throw new Error('The server returned an invalid upload response.');}}if(!r.ok){if(r.status===401)throw new Error('Your admin session expired. Please sign in again.');if(r.status===403)throw new Error('The image upload was rejected. Your account remains signed in; please retry.');if(r.status===413)throw new Error('Image is too large. Choose an image under 5 MB.');throw new Error(data.error||data.detail||data.message||('Image upload failed (HTTP '+r.status+')'));}if(!data.url)throw new Error('Image upload completed without a file URL.');return data;});}).then(function(data){var field=$('#homepage-form [name="'+fieldName+'"]');field.value=API+'/'+String(data.url||'').replace(/^\/+/, '').replace(/^api\//,'');updateHomepagePresetSelection();status.textContent='Image uploaded. Save the home page to publish it.';}).catch(function(error){status.textContent=error.message;}).finally(function(){input.disabled=false;input.value='';});}
  $('#homepage-desktop-file').onchange=function(){uploadHomepageImage(this,'heroImage');};
  $('#homepage-mobile-file').onchange=function(){uploadHomepageImage(this,'heroMobileImage');};
  function loadHomepage(){var status=$('#homepage-status');status.textContent='Loading…';return fetch(API+'/homepage',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Could not load home page settings');return r.json();}).then(function(data){homepageFields().forEach(function(field){field.value=data[field.name]||'';});updateHomepagePresetSelection();status.textContent='';}).catch(function(error){status.textContent=error.message;});}
  $('#homepage-form').onsubmit=function(event){event.preventDefault();var status=$('#homepage-status'),button=event.currentTarget.querySelector('[type="submit"]'),payload={};homepageFields().forEach(function(field){payload[field.name]=field.value.trim();});button.disabled=true;status.textContent='Saving…';fetch(API+'/homepage',{method:'PUT',headers:adminHeaders({'Content-Type':'application/json'}),body:JSON.stringify(payload)}).then(function(r){return r.text().then(function(text){var body={};if(text){try{body=JSON.parse(text);}catch(error){if(r.ok)throw new Error('The server returned an invalid response. Please try again.');}}if(!r.ok){if(r.status===401||r.status===403){sessionStorage.removeItem('clearly_admin_token');showLogin('Your admin session expired. Please sign in again.');throw new Error('Your admin session expired. Please sign in again.');}throw new Error(body.error||body.detail||body.message||('Could not save home page (HTTP '+r.status+')'));}return body;});}).then(function(data){homepageFields().forEach(function(field){if(Object.prototype.hasOwnProperty.call(data,field.name))field.value=data[field.name]||'';});updateHomepagePresetSelection();status.textContent='Home page updated successfully.';localStorage.setItem('clearly_homepage_revision',String(Date.now()));}).catch(function(error){status.textContent=error.message;}).finally(function(){button.disabled=false;});};

  renderHomepagePresets();

  renderSchema();fetch('mysql-schema.sql').then(function(r){if(!r.ok)throw new Error();return r.text();}).then(function(sql){schemaText=sql;$('#schema-preview').textContent=sql;}).catch(function(){});fetch(API+'/catalog').then(function(r){return r.json();}).then(function(data){catalog=data||catalog;renderCatalog();populateProductOptions();}).catch(function(){renderCatalog();});loadProducts().catch(function(e){$('#products-table').innerHTML='<div class="empty">'+esc(e.message)+'</div>';});var initialView=new URLSearchParams(location.search).get('view');if(['products','users','homepage','catalog','database'].includes(initialView))showView(initialView);verifyAdmin(adminToken());
})();
